version: '3.9'

services:
  db:
    image: mariadb:jammy
    restart: always
    volumes:
      - /docker/weatherstation/data:/var/lib/mysql
    command: --max_allowed_packet=32505856 '--wait_timeout=28800'
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: master_data_base
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20

  datahandler:
    image: jerey/weatherstation-datahandler:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:  
      DB_HOST: db
    restart: on-failure
    
  weatherstation_server:
    image: jerey/weatherstation-server:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always 
    container_name: mosquitto
    network_mode: host
    ports:
      - "1883:1883"
      - "9001:9001"
