name: CI to docker hub

on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./webserver
      - run: npm test
        working-directory: ./webserver


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./webserver
          file: ./webserver/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/weatherstation-server:latest
          

      - name: Image digest
        run: echo ${{ steps.docker_build_server.outputs.digest }}
        
        
      - name: Build and push
        id: docker_build_datahandler
        uses: docker/build-push-action@v2
        with:
          context: ./datahandler
          file: ./datahandler/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/weatherstation-datahandler:latest
          

      - name: Image digest
        run: echo ${{ steps.docker_build_datahandler.outputs.digest }}
