name: Pull request

on:
  push:
    branches: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ./webserver
      - run: npm test
        working-directory: ./webserver
